// Writes lib/firebase_web_options.dart from environment variables (CI / local).
// If FIREBASE_WEB_API_KEY is unset, exits 0 without modifying the file.

import 'dart:io';

String _dartStr(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

void main() {
  String? env(String k) {
    final v = Platform.environment[k];
    if (v == null) return null;
    final t = v.trim();
    return t.isEmpty ? null : t;
  }

  final apiKey = env('FIREBASE_WEB_API_KEY');
  final appId = env('FIREBASE_WEB_APP_ID');
  if (apiKey == null || appId == null) {
    stderr.writeln(
      'inject_firebase_web_options: no FIREBASE_WEB_API_KEY / FIREBASE_WEB_APP_ID; '
      'keeping existing lib/firebase_web_options.dart.',
    );
    exit(0);
  }

  final messagingSenderId = env('FIREBASE_WEB_MESSAGING_SENDER_ID');
  final projectId = env('FIREBASE_WEB_PROJECT_ID');
  final storageBucket = env('FIREBASE_WEB_STORAGE_BUCKET');
  if (messagingSenderId == null ||
      projectId == null ||
      storageBucket == null) {
    stderr.writeln(
      'inject_firebase_web_options: also need '
      'FIREBASE_WEB_MESSAGING_SENDER_ID, FIREBASE_WEB_PROJECT_ID, '
      'FIREBASE_WEB_STORAGE_BUCKET.',
    );
    exit(1);
  }

  final authDomain =
      env('FIREBASE_WEB_AUTH_DOMAIN') ?? '$projectId.firebaseapp.com';
  final measurementId = env('FIREBASE_WEB_MEASUREMENT_ID');

  final b = StringBuffer()
    ..writeln("import 'package:firebase_core/firebase_core.dart';")
    ..writeln()
    ..writeln('/// Generated by tool/inject_firebase_web_options.dart.')
    ..writeln('abstract final class FirebaseWebOptions {')
    ..writeln('  static const FirebaseOptions current = FirebaseOptions(')
    ..writeln("    apiKey: '${_dartStr(apiKey)}',")
    ..writeln("    appId: '${_dartStr(appId)}',")
    ..writeln("    messagingSenderId: '${_dartStr(messagingSenderId)}',")
    ..writeln("    projectId: '${_dartStr(projectId)}',")
    ..writeln("    authDomain: '${_dartStr(authDomain)}',")
    ..writeln("    storageBucket: '${_dartStr(storageBucket)}',");

  if (measurementId != null) {
    b.writeln("    measurementId: '${_dartStr(measurementId)}',");
  }

  b
    ..writeln('  );')
    ..writeln()
    ..writeln('  static bool get isConfigured =>')
    ..writeln('      current.apiKey.isNotEmpty &&')
    ..writeln('      current.appId.isNotEmpty &&')
    ..writeln("      !current.apiKey.startsWith('REPLACE_');")
    ..writeln('}');

  File('lib/firebase_web_options.dart').writeAsStringSync(b.toString());
  stdout.writeln('Wrote lib/firebase_web_options.dart from environment.');
}
