#!/usr/bin/env python3
"""Build lib/data/ai_chat/starter_quick_reply_en_translations.dart from ja→en map."""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DART_IN = ROOT / "lib/data/ai_chat/starter_quick_replies_by_problem_id.dart"
DART_OUT = ROOT / "lib/data/ai_chat/starter_quick_reply_en_translations.dart"
MAP_JSON = Path(__file__).resolve().parent / "starter_quick_reply_ja_en.json"


def collect_strings() -> tuple[list[str], list[str]]:
    text = DART_IN.read_text(encoding="utf-8")
    labels = sorted(set(re.findall(r'label: "([^"]+)"', text)))
    sends = sorted(set(re.findall(r'sendText: "([^"]+)"', text)))
    return labels, sends


def load_map() -> dict[str, str]:
    if not MAP_JSON.exists():
        raise SystemExit(f"Missing {MAP_JSON}")
    data = json.loads(MAP_JSON.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("ja_en map must be a JSON object")
    return {str(k): str(v) for k, v in data.items()}


def dart_escape(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit_dart(mapping: dict[str, str], labels: list[str], sends: list[str]) -> None:
  missing = [s for s in labels + sends if s not in mapping]
  if missing:
    print(f"Missing {len(missing)} translations:")
    for s in missing[:20]:
      print(f"  - {s}")
    if len(missing) > 20:
      print(f"  ... and {len(missing) - 20} more")
    raise SystemExit(1)

  lines = [
    "// GENERATED by tool/local/ai_starter_codegen/build_starter_quick_reply_en_dart.py",
    "// Edit starter_quick_reply_ja_en.json and re-run the script.",
    "",
    "/// Japanese label/sendText → English for starter quick-reply chips.",
    "const starterQuickReplyJaToEn = <String, String>{",
  ]
  for key in sorted(mapping.keys(), key=lambda x: (x not in labels + sends, x)):
    lines.append(f"  {dart_escape(key)}: {dart_escape(mapping[key])},")
  lines.append("};")
  lines.append("")
  DART_OUT.write_text("\n".join(lines), encoding="utf-8")
  print(f"Wrote {DART_OUT} ({len(mapping)} entries)")


def main() -> None:
  labels, sends = collect_strings()
  mapping = load_map()
  emit_dart(mapping, labels, sends)


if __name__ == "__main__":
  main()
